import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./Components/Sidebar/Sidebar";
import Header from "./Components/Header/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Espotefai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: "flex" }}>
        <Sidebar />
        <Header />
        {children}
      </body>
    </html>
  );
}
