import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./Components/Sidebar/Sidebar";
import Footer from "./Components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Espotefaison",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ display: "flex", flex: "row", gap: "20px" }}>
          <Sidebar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
