import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./Components/Sidebar/Sidebar";
import Header from "./Components/Header/Header";
import Footer from "./Components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Espotefai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: "flex" }}>
        <div style={{ display: "flex", flex: "row", gap: "20px" }}>
          <Sidebar />
          <div style={{ display: "flex", flexDirection: "column", width:"100%" }}>
          <Header />
            <Footer />
        </div>
        </div>
      </body>
    </html>
  );
}
